apiVersion: v1
kind: ConfigMap
metadata:
  name: minitube
  namespace: minitube
data:
  HTTP_ADDR: ":8080"
  PUBLIC_BASE_URL: "https://minitube.19121122.xyz"
  UPLOAD_DIR: "/data/uploads"
  SRS_HLS_DIR: "/data/srs-hls"
  LIVE_HLS_DIR: "/data/live-hls"
  RTMP_BASE_URL: "rtmp://192.168.43.111:1935/live"
  LIVE_IDLE_TTL: "1h"
  ACCESS_TOKEN_TTL: "168h"
  ADMIN_USER_IDS: "2c6197a8-0c7d-497d-989f-ae8407fb28f3,c046ddd3-5b1b-4171-8f1e-d0c545dafe2c"
  NFS_SERVER: "192.168.43.131"
  MEDIA_EDGE_TLS_ADDR: ":18080"
  MEDIA_EDGE_TLS_CERT: "/data/ctc-tls/fullchain.pem"
  MEDIA_EDGE_TLS_KEY: "/data/ctc-tls/privkey.pem"
  MEDIA_EDGE_TLS_HOST: "ctc.minitube.19121122.xyz"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minitube-srs
  namespace: minitube
data:
  srs.conf: |
    listen              1935;
    max_connections     1000;
    daemon              off;
    srs_log_tank        console;

    http_api {
        enabled         on;
        listen          1985;
    }

    http_server {
        enabled         on;
        listen          8080;
        dir             /data/srs-hls;
    }

    vhost __defaultVhost__ {
        tcp_nodelay     on;

        hls {
            enabled             on;
            hls_path            /data/srs-hls;
            hls_fragment        2;
            hls_window          86400;
            hls_wait_keyframe   on;
            hls_cleanup         off;
            hls_dispose         0;
            hls_m3u8_file       [app]/[stream].m3u8;
            hls_ts_file         [app]/[stream]-[seq].ts;
            hls_on_error        continue;
        }

        http_hooks {
            enabled         on;
            on_publish      http://minitube-api:8080/v1/internal/srs/on_publish?secret=SRS_HOOK_SECRET;
            on_unpublish    http://minitube-api:8080/v1/internal/srs/on_unpublish?secret=SRS_HOOK_SECRET;
            on_hls          http://minitube-api:8080/v1/internal/srs/on_hls?secret=SRS_HOOK_SECRET;
        }
    }
