apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - quota.yaml
  - limitrange.yaml
  - pvc.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - srs.yaml
  - workers.yaml
