apiVersion: v1
kind: PersistentVolume
metadata:
  name: minitube-media-test
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - actimeo=10
  nfs:
    server: 192.168.43.131
    path: /data/minitube-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minitube-media
  namespace: minitube-test
spec:
  accessModes:
    - ReadWriteMany
  volumeName: minitube-media-test
  resources:
    requests:
      storage: 50Gi
