apiVersion: v1
kind: ResourceQuota
metadata:
  name: minitube-test
  namespace: minitube-test
spec:
  hard:
    pods: "16"
    persistentvolumeclaims: "4"
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "32"
    limits.memory: 16Gi
