apiVersion: v1
kind: Service
metadata:
  name: minitube-srs
  namespace: minitube-test
spec:
  ports:
    - name: rtmp
      port: 1936
      targetPort: 1936
    - name: api
      port: 1985
      targetPort: 1985
  selector:
    app: minitube-srs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitube-srs
  namespace: minitube-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minitube-srs
  template:
    metadata:
      labels:
        app: minitube-srs
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: srs
          image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
          imagePullPolicy: IfNotPresent
          env:
            - name: SRS_HOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: minitube
                  key: SRS_HOOK_SECRET
          command: ["/bin/sh", "-c"]
          args:
            - sed "s/SRS_HOOK_SECRET/${SRS_HOOK_SECRET}/g" /cfg/srs.conf > /tmp/srs.conf && exec ./objs/srs -c /tmp/srs.conf
          ports:
            - containerPort: 1936
              hostPort: 1936
            - containerPort: 1985
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: cfg
              mountPath: /cfg
              readOnly: true
            - name: media
              mountPath: /data
      volumes:
        - name: cfg
          configMap:
            name: minitube-srs
        - name: media
          persistentVolumeClaim:
            claimName: minitube-media
